# Generated by Django 3.2.19 on 2023-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
