version: '3.7'

services:
  tehmet:
    build: .
    networks:
      - proxy
    env_file:
      - .env
    command: sh start.sh
    depends_on:
      - postgres
      - redis
    volumes:
    - .:/code
    - ./media/:/media/

  postgres:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5437:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data_atl/

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - tehmet
    volumes:
      - ./media/:/media/

  celery:
    build: .
    env_file:
      - .env
    command: celery -A core worker -B -l info
    restart: always
    depends_on:
      - tehmet
      - redis

  redis:
    hostname: redis
    image: redis:alpine
    expose:
      - 6379

volumes:
  postgres_data:
  media_data:
